services:
  bluesquare.validator:
    class: Bluesquare\ValidatorBundle\Validator
    autowire: true
    public: true
    arguments: ['@request_stack', '@translator.data_collector']
  Bluesquare\ValidatorBundle\Validator: '@bluesquare.validator'
