services:
  _default:
    autowire: true
    autoconfigure: true
  Bluesquare\Validator:
    class: Bluesquare\ValidatorBundle
    autowire: true
    autoconfigure: true
    arguments: ['@symfony/request-stack']
